# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
 
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}.0

# branches to build
branches:
  # whitelist
  only:
    - master
    
# Do not build on tag (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
#environment:
#  VisualStudioVersion: 12.0
  
# Operating system (build VM template)
os: unstable

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\TortoiseSI

# this is how to allow failing jobs in the matrix
matrix:
  # set this flag to immediately finish build once one of the jobs fails.
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release
      
# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo Repository cloned
  - echo "APPVEYOR_BUILD_VERSION ->"
  - echo %APPVEYOR_BUILD_VERSION%

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64
 
# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU
 
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
 
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
 

      
build:
  parallel: true                 # enable MSBuild parallel builds
  project: src/TortoiseSI.sln    # path to Visual Studio solution or project
 
  # MSBuild verbosity level
  verbosity: normal
 
 
# scripts to run before build
before_build:
  - ps: .\updateInstallerVersion.ps1 $Env:APPVEYOR_BUILD_VERSION

# scripts to run after build
after_build:
 
# to run your custom scripts instead of automatic MSBuild
build_script:
 
# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# test configuration here

# to disable automatic tests
#test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
# Tells AppVeyor which file and folders should be uploaded to AppVeyor cloud storage
# during the build

artifacts: |
  if($Env:Platform -eq "Win32")
  {
    Push-AppveyorArtifact "\bin\Release\bin\TortoiseSI32.dll"
  }
  if($Env:Platform -eq "x64")
  {
    Push-AppveyorArtifact "\bin\setup\x64\TortoiseSI.msi"
  }


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deployment configuration here

#---------------------------------#
#        global handlers          #
#---------------------------------#
 
# on successful build
on_success:
#  - do something
 
# on build failure
on_failure:
#  - do something
 
# after build failure or success
on_finish:
#  - do something
 
#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
 
  # Email
  - provider: Email
    to:
      - gisraeli@ptc.com
      - krtaylor@ptc.com
      - szhao@ptc.com
      - bleskowsky@ptc.com
      - crovers@ptc.com
    subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true